@startuml
class Ticket {
    Класс Тикет
    ..
    title : Заголовок тикета
    description: Описание тикета
    state: Состояние тикета
    author: Автор тикета
    actor: Назначенный исполнитель
    created_at: Дата создания
    updated_at: Дата обновления
}
class TicketHistory{
    Класс для хранения истории изменения состояний тикета
    ..
    ticket: Тикет
    ticket_state: Состояние тикета в момент создания записи
    created_at: Дата создания
}

class User {
    Класс пользователя
    ..
    username: Имя пользователя (login)
    password: Пароль
}
class Token {
    Класс Токен атворизации
    ..
    user: Пользователь
    token: Токен атворизации
}
@enduml

