version: '3'

services:

  web:
    image: nginx
    restart: always
    depends_on:
    - django
    ports:
    - '80:80'
    volumes:
    - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./public:/code/public

  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    ports:
    - '5432:5432'

  django:
    build: .
    command: sh -c "/code/deploy/run.sh"
    restart: always
    volumes:
      - .:/code
    ports:
      - '8080:8080'
    depends_on:
      - db

