# Generated by Django 2.1.1 on 2018-09-23 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20180923_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'История',
            },
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': (('view_statistic', 'Может просматривать статистику по тикетам'), ('can_create', 'Может создавать тикеты'), ('can_view', 'Может просматривать тикет'), ('close_reopen', 'Может закрыть/переоткрыть тикет'), ('proceed_done_cancel', 'Может обрабатывать/завершать/отменять тикет')), 'verbose_name': 'Тикет', 'verbose_name_plural': 'Тикеты'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=django_fsm.FSMField(choices=[(0, 'Новый'), (1, 'Назначен'), (2, 'Обрабатывается'), (3, 'Выполнен'), (4, 'Закрыт'), (5, 'Отменен'), (6, 'Переоткрыт')], default=(0, 'Новый'), max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='actor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='statement',
            field=models.IntegerField(choices=[(0, 'Новый'), (1, 'Назначен'), (2, 'Обрабатывается'), (3, 'Выполнен'), (4, 'Закрыт'), (5, 'Отменен'), (6, 'Переоткрыт')], default=0, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='history', to='ticket.Ticket', verbose_name='Тикет'),
        ),
    ]
