# Generated by Django 2.1.1 on 2018-09-23 18:31

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20180923_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=django_fsm.FSMField(choices=[('Новый', 'Новый'), ('Назначен', 'Назначен'), ('Обрабатывается', 'Обрабатывается'), ('Выполнен', 'Выполнен'), ('Закрыт', 'Закрыт'), ('Отменен', 'Отменен'), ('Переоткрыт', 'Переоткрыт')], default=('Новый', 'Новый'), max_length=50, verbose_name='Состояние тикета'),
        ),
    ]
