# Generated by Django 2.1.1 on 2018-09-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20180923_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='statement',
        ),
    ]
