# Generated by Django 2.1.1 on 2018-10-06 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20180923_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickethistory',
            name='ticket',
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='ticket_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Id тикета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='ticket_state',
            field=models.CharField(default='new', max_length=255, verbose_name='Состояния тикета'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=django_fsm.FSMField(choices=[('new', 'Новый'), ('assigned', 'Назначен'), ('processed', 'Обрабатывается'), ('done', 'Выполнен'), ('close', 'Закрыт'), ('canceled', 'Отменен'), ('reopen', 'Переоткрыт')], default='new', max_length=50, verbose_name='Состояние тикета'),
        ),
    ]
