# Generated by Django 2.1.1 on 2018-10-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20181006_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': (('can_view_statistic', 'Может просматривать статистику по тикетам'), ('can_create', 'Может создавать тикеты'), ('can_view', 'Может просматривать тикет'), ('close_reopen', 'Может закрыть/переоткрыть тикет'), ('proceed_done_cancel', 'Может обрабатывать/завершать/отменять тикет')), 'verbose_name': 'Тикет', 'verbose_name_plural': 'Тикеты'},
        ),
    ]
