# Generated by Django 2.1.1 on 2018-10-06 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20181006_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickethistory',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ticket.Ticket', verbose_name='Тикет'),
            preserve_default=False,
        ),
    ]
